2022 03 15 travis fail
brain-score/brainio pull request #18
Opened 2022-03-25 19:36 UTC by jjpr-mit

2022-03-27 09:01 UTC, mschrimpf requested changes

2022-03-27 09:01 UTC, mschrimpf commented on .travis.yml
> +- pip list
redundant with line 18/20 (travis does this anyway, I think both can go)

2022-03-29 14:10 UTC, mike-ferguson approved these changes

2022-03-29 18:27 UTC, mschrimpf approved these changes

2022-03-29 18:29 UTC, merged