add documentation on configuring AWS access
brain-score/brainio pull request #31
Opened 2022-10-14 16:23 UTC by mschrimpf

2022-10-16 16:57 UTC, mschrimpf commented
should pass after https://github.com/brain-score/brainio/pull/30 is merged

2022-10-17 17:02 UTC, mschrimpf commented
re-trigger

2022-10-24 17:53 UTC, jjpr-mit requested changes

2022-10-24 17:53 UTC, jjpr-mit commented on docs/aws_access.md
> +You do not need AWS access to download many files as long as they are public.
Wording is a little awkward.  I propose:  

> You do not need AWS credentials to download public files. 
> 
> To download private files or to upload files to S3, you will need an admin to create a user for you.
> After you have received your credentials, you can configure your access in two ways:

2022-10-24 18:02 UTC, jjpr-mit approved these changes

2022-10-24 18:25 UTC, merged